apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: "postgres-svc"
    port: 5432
    targetPort: 5432