apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deploy
  labels:
    name: postgres-db
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-db
      app: voting-app
  template:
    metadata:
      name: postgres-db
      labels:
        name: postgres-db
        app: voting-app
    spec:
      containers:
      - name: postgres-pod
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust