apiVersion: v1
kind: Service
metadata:
  name: db # As same as value in worker-app: Server=db
  labels:
    name: postgres-svc
    app: voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-db
    app: voting-app