apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    name: redis-db
    app: voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-db
    app: voting-app