apiVersion: v1
kind: Service
metadata:
  name: redis # As same as value in worker-app: var redisConn = OpenRedisConnection("redis")
  labels:
    name: redis-svc
    app: voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-db
    app: voting-app