apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-db
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-db
      app: voting-app
  template:
    metadata:
      name: redis-db
      labels:
        name: redis-db
        app: voting-app
    spec:
      containers:
      - name: redis-pod
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379