apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: result-app
spec:
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: tresvitae/result-app:v1
        ports:
        - containerPort: 80