apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-svc
spec:
  type: NodePort
  ports:
  - name: result-svc
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result