apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-deploy
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result-pod
        image: tresvitae/result-app:v1
        ports:
        - name: result
          containerPort: 80
