apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    app: result-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    app: result-app