apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app
    app: voting-app
spec:
  selector:
    matchLabels:
      name: result-app
      app: voting-app
  template:
    metadata:
      name: result-app
      labels:
        name: result-app
        app: voting-app
    spec:
      containers:
      - name: result-pod
        image: tresvitae/result-app:v1
        ports:
        - containerPort: 80