apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-app
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote-pod
        image: tresvitae/vote-app:v1.1
        ports:
        - name: vote-pod
          containerPort: 80
