apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: vote-app
    app: voting-app
spec:
  selector:
    matchLabels:
      name: vote-app
      app: voting-app
  template:
    metadata:
      name: vote-app
      labels:
        name: vote-app
        app: voting-app
    spec:
      containers:
      - name: vote-pod
        image: tresvitae/vote-app:v2
        ports:
        - containerPort: 80