apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-svc
spec:
  type: NodePort
  ports:
  - name: vote-svc
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
