apiVersion: v1
kind: Service
metadata:
  name: vote-svc
  labels:
    name: vote-app
    app: voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
  selector:
    name: vote-app
    app: voting-app