apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
      app: voting-app
  template:
    metadata:
      name: worker-app
      labels:
        name: worker-app
        app: voting-app
    spec:
      containers:
      - name: worker-pod
        image: tresvitae/worker-app:v2
---